packages:
  core: !include dfltech-switch.yaml

esphome:
  project:
    name: dflourusso.dfltech-switch
    version: 1.0.6

http_request:
  verify_ssl: false
  tls_buffer_size_rx: 2048

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: Firmware
    device_class: firmware
    source: https://dflourusso.github.io/ha-esphome-switch/firmware/manifest.json
