packages:
  core: !include dfltech-switch.yaml

esphome:
  project:
    name: dflourusso.dfltech-switch
    version: "2.2.0"

http_request:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: Firmware
    device_class: firmware
    source: https://dflourusso.github.io/ha-esphome-switch/firmware/manifest.json
